"""Add user_friends UniqueConstraint.

Revision ID: 10677ee9b178
Revises: a98d22d7b75a
Create Date: 2023-11-17 16:36:41.216545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10677ee9b178'
down_revision: Union[str, None] = 'a98d22d7b75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_friends', 'user_friends', ['vk_user_id', 'friend_vk_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_friends', 'user_friends', type_='unique')
    # ### end Alembic commands ###
