"""VKUser model friends relationship creation v2.

Revision ID: a98d22d7b75a
Revises: c0be1ccbd453
Create Date: 2023-11-16 23:52:23.454137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98d22d7b75a'
down_revision: Union[str, None] = 'c0be1ccbd453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_group_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_groups_id'), 'vk_groups', ['id'], unique=False)
    op.create_index(op.f('ix_vk_groups_vk_group_id'), 'vk_groups', ['vk_group_id'], unique=True)
    op.create_table('vk_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_users_id'), 'vk_users', ['id'], unique=False)
    op.create_index(op.f('ix_vk_users_vk_user_id'), 'vk_users', ['vk_user_id'], unique=True)
    op.create_table('user_friends',
    sa.Column('vk_user_id', sa.Integer(), nullable=False),
    sa.Column('friend_vk_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_vk_user_id'], ['vk_users.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('vk_user_id', 'friend_vk_user_id')
    )
    op.create_table('user_groups',
    sa.Column('vk_user_id', sa.Integer(), nullable=True),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    op.drop_table('user_friends')
    op.drop_index(op.f('ix_vk_users_vk_user_id'), table_name='vk_users')
    op.drop_index(op.f('ix_vk_users_id'), table_name='vk_users')
    op.drop_table('vk_users')
    op.drop_index(op.f('ix_vk_groups_vk_group_id'), table_name='vk_groups')
    op.drop_index(op.f('ix_vk_groups_id'), table_name='vk_groups')
    op.drop_table('vk_groups')
    # ### end Alembic commands ###
